
DROP TABLE IF EXISTS brainwaves CASCADE ;
DROP TABLE IF EXISTS readings CASCADE ;
DROP TABLE IF EXISTS sensor_data CASCADE ;
DROP TABLE IF EXISTS sessions CASCADE ;
DROP TABLE IF EXISTS users  CASCADE ;
DROP TABLE IF EXISTS sensor_readings CASCADE ;
DROP TYPE IF EXISTS sex CASCADE ;
DROP TYPE IF EXISTS session_type CASCADE ;
DROP TYPE IF EXISTS unit CASCADE ;